// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package doppler

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-doppler/sdk/go/doppler/internal"
)

var _ = internal.GetEnvOrDefault

type WebhookAuthentication struct {
	Password *string `pulumi:"password"`
	Token    *string `pulumi:"token"`
	Type     string  `pulumi:"type"`
	Username *string `pulumi:"username"`
}

// WebhookAuthenticationInput is an input type that accepts WebhookAuthenticationArgs and WebhookAuthenticationOutput values.
// You can construct a concrete instance of `WebhookAuthenticationInput` via:
//
//	WebhookAuthenticationArgs{...}
type WebhookAuthenticationInput interface {
	pulumi.Input

	ToWebhookAuthenticationOutput() WebhookAuthenticationOutput
	ToWebhookAuthenticationOutputWithContext(context.Context) WebhookAuthenticationOutput
}

type WebhookAuthenticationArgs struct {
	Password pulumi.StringPtrInput `pulumi:"password"`
	Token    pulumi.StringPtrInput `pulumi:"token"`
	Type     pulumi.StringInput    `pulumi:"type"`
	Username pulumi.StringPtrInput `pulumi:"username"`
}

func (WebhookAuthenticationArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*WebhookAuthentication)(nil)).Elem()
}

func (i WebhookAuthenticationArgs) ToWebhookAuthenticationOutput() WebhookAuthenticationOutput {
	return i.ToWebhookAuthenticationOutputWithContext(context.Background())
}

func (i WebhookAuthenticationArgs) ToWebhookAuthenticationOutputWithContext(ctx context.Context) WebhookAuthenticationOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WebhookAuthenticationOutput)
}

func (i WebhookAuthenticationArgs) ToWebhookAuthenticationPtrOutput() WebhookAuthenticationPtrOutput {
	return i.ToWebhookAuthenticationPtrOutputWithContext(context.Background())
}

func (i WebhookAuthenticationArgs) ToWebhookAuthenticationPtrOutputWithContext(ctx context.Context) WebhookAuthenticationPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WebhookAuthenticationOutput).ToWebhookAuthenticationPtrOutputWithContext(ctx)
}

// WebhookAuthenticationPtrInput is an input type that accepts WebhookAuthenticationArgs, WebhookAuthenticationPtr and WebhookAuthenticationPtrOutput values.
// You can construct a concrete instance of `WebhookAuthenticationPtrInput` via:
//
//	        WebhookAuthenticationArgs{...}
//
//	or:
//
//	        nil
type WebhookAuthenticationPtrInput interface {
	pulumi.Input

	ToWebhookAuthenticationPtrOutput() WebhookAuthenticationPtrOutput
	ToWebhookAuthenticationPtrOutputWithContext(context.Context) WebhookAuthenticationPtrOutput
}

type webhookAuthenticationPtrType WebhookAuthenticationArgs

func WebhookAuthenticationPtr(v *WebhookAuthenticationArgs) WebhookAuthenticationPtrInput {
	return (*webhookAuthenticationPtrType)(v)
}

func (*webhookAuthenticationPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**WebhookAuthentication)(nil)).Elem()
}

func (i *webhookAuthenticationPtrType) ToWebhookAuthenticationPtrOutput() WebhookAuthenticationPtrOutput {
	return i.ToWebhookAuthenticationPtrOutputWithContext(context.Background())
}

func (i *webhookAuthenticationPtrType) ToWebhookAuthenticationPtrOutputWithContext(ctx context.Context) WebhookAuthenticationPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WebhookAuthenticationPtrOutput)
}

type WebhookAuthenticationOutput struct{ *pulumi.OutputState }

func (WebhookAuthenticationOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*WebhookAuthentication)(nil)).Elem()
}

func (o WebhookAuthenticationOutput) ToWebhookAuthenticationOutput() WebhookAuthenticationOutput {
	return o
}

func (o WebhookAuthenticationOutput) ToWebhookAuthenticationOutputWithContext(ctx context.Context) WebhookAuthenticationOutput {
	return o
}

func (o WebhookAuthenticationOutput) ToWebhookAuthenticationPtrOutput() WebhookAuthenticationPtrOutput {
	return o.ToWebhookAuthenticationPtrOutputWithContext(context.Background())
}

func (o WebhookAuthenticationOutput) ToWebhookAuthenticationPtrOutputWithContext(ctx context.Context) WebhookAuthenticationPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v WebhookAuthentication) *WebhookAuthentication {
		return &v
	}).(WebhookAuthenticationPtrOutput)
}

func (o WebhookAuthenticationOutput) Password() pulumi.StringPtrOutput {
	return o.ApplyT(func(v WebhookAuthentication) *string { return v.Password }).(pulumi.StringPtrOutput)
}

func (o WebhookAuthenticationOutput) Token() pulumi.StringPtrOutput {
	return o.ApplyT(func(v WebhookAuthentication) *string { return v.Token }).(pulumi.StringPtrOutput)
}

func (o WebhookAuthenticationOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v WebhookAuthentication) string { return v.Type }).(pulumi.StringOutput)
}

func (o WebhookAuthenticationOutput) Username() pulumi.StringPtrOutput {
	return o.ApplyT(func(v WebhookAuthentication) *string { return v.Username }).(pulumi.StringPtrOutput)
}

type WebhookAuthenticationPtrOutput struct{ *pulumi.OutputState }

func (WebhookAuthenticationPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**WebhookAuthentication)(nil)).Elem()
}

func (o WebhookAuthenticationPtrOutput) ToWebhookAuthenticationPtrOutput() WebhookAuthenticationPtrOutput {
	return o
}

func (o WebhookAuthenticationPtrOutput) ToWebhookAuthenticationPtrOutputWithContext(ctx context.Context) WebhookAuthenticationPtrOutput {
	return o
}

func (o WebhookAuthenticationPtrOutput) Elem() WebhookAuthenticationOutput {
	return o.ApplyT(func(v *WebhookAuthentication) WebhookAuthentication {
		if v != nil {
			return *v
		}
		var ret WebhookAuthentication
		return ret
	}).(WebhookAuthenticationOutput)
}

func (o WebhookAuthenticationPtrOutput) Password() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *WebhookAuthentication) *string {
		if v == nil {
			return nil
		}
		return v.Password
	}).(pulumi.StringPtrOutput)
}

func (o WebhookAuthenticationPtrOutput) Token() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *WebhookAuthentication) *string {
		if v == nil {
			return nil
		}
		return v.Token
	}).(pulumi.StringPtrOutput)
}

func (o WebhookAuthenticationPtrOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *WebhookAuthentication) *string {
		if v == nil {
			return nil
		}
		return &v.Type
	}).(pulumi.StringPtrOutput)
}

func (o WebhookAuthenticationPtrOutput) Username() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *WebhookAuthentication) *string {
		if v == nil {
			return nil
		}
		return v.Username
	}).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*WebhookAuthenticationInput)(nil)).Elem(), WebhookAuthenticationArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*WebhookAuthenticationPtrInput)(nil)).Elem(), WebhookAuthenticationArgs{})
	pulumi.RegisterOutputType(WebhookAuthenticationOutput{})
	pulumi.RegisterOutputType(WebhookAuthenticationPtrOutput{})
}
