// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package doppler

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func Secrets(ctx *pulumi.Context, args *SecretsArgs, opts ...pulumi.InvokeOption) (*SecretsResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv SecretsResult
	err := ctx.Invoke("doppler:index/secrets:Secrets", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking Secrets.
type SecretsArgs struct {
	Config  *string `pulumi:"config"`
	Project *string `pulumi:"project"`
}

// A collection of values returned by Secrets.
type SecretsResult struct {
	Config *string `pulumi:"config"`
	// The provider-assigned unique ID for this managed resource.
	Id      string            `pulumi:"id"`
	Map     map[string]string `pulumi:"map"`
	Project *string           `pulumi:"project"`
}

func SecretsOutput(ctx *pulumi.Context, args SecretsOutputArgs, opts ...pulumi.InvokeOption) SecretsResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (SecretsResult, error) {
			args := v.(SecretsArgs)
			r, err := Secrets(ctx, &args, opts...)
			var s SecretsResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(SecretsResultOutput)
}

// A collection of arguments for invoking Secrets.
type SecretsOutputArgs struct {
	Config  pulumi.StringPtrInput `pulumi:"config"`
	Project pulumi.StringPtrInput `pulumi:"project"`
}

func (SecretsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*SecretsArgs)(nil)).Elem()
}

// A collection of values returned by Secrets.
type SecretsResultOutput struct{ *pulumi.OutputState }

func (SecretsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*SecretsResult)(nil)).Elem()
}

func (o SecretsResultOutput) ToSecretsResultOutput() SecretsResultOutput {
	return o
}

func (o SecretsResultOutput) ToSecretsResultOutputWithContext(ctx context.Context) SecretsResultOutput {
	return o
}

func (o SecretsResultOutput) Config() pulumi.StringPtrOutput {
	return o.ApplyT(func(v SecretsResult) *string { return v.Config }).(pulumi.StringPtrOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o SecretsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v SecretsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o SecretsResultOutput) Map() pulumi.StringMapOutput {
	return o.ApplyT(func(v SecretsResult) map[string]string { return v.Map }).(pulumi.StringMapOutput)
}

func (o SecretsResultOutput) Project() pulumi.StringPtrOutput {
	return o.ApplyT(func(v SecretsResult) *string { return v.Project }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(SecretsResultOutput{})
}
