// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Doppler
{
    /// <summary>
    /// Manage a Doppler project service account member.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Doppler = Pulumiverse.Doppler;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var backendCi = new Doppler.ProjectMemberServiceAccount("backend_ci", new()
    ///     {
    ///         Project = "backend",
    ///         ServiceAccountSlug = ci.Slug,
    ///         Role = "viewer",
    ///         Environments = new[]
    ///         {
    ///             "dev",
    ///             "stg",
    ///             "prd",
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// </summary>
    [DopplerResourceType("doppler:index/projectMemberServiceAccount:ProjectMemberServiceAccount")]
    public partial class ProjectMemberServiceAccount : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The environments in the project where this access will apply (null or omitted for roles with access to all environments)
        /// </summary>
        [Output("environments")]
        public Output<ImmutableArray<string>> Environments { get; private set; } = null!;

        /// <summary>
        /// The name of the Doppler project where the access is applied
        /// </summary>
        [Output("project")]
        public Output<string> Project { get; private set; } = null!;

        /// <summary>
        /// The project role identifier for the access
        /// </summary>
        [Output("role")]
        public Output<string> Role { get; private set; } = null!;

        /// <summary>
        /// The slug of the Doppler service account
        /// </summary>
        [Output("serviceAccountSlug")]
        public Output<string> ServiceAccountSlug { get; private set; } = null!;


        /// <summary>
        /// Create a ProjectMemberServiceAccount resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ProjectMemberServiceAccount(string name, ProjectMemberServiceAccountArgs args, CustomResourceOptions? options = null)
            : base("doppler:index/projectMemberServiceAccount:ProjectMemberServiceAccount", name, args ?? new ProjectMemberServiceAccountArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ProjectMemberServiceAccount(string name, Input<string> id, ProjectMemberServiceAccountState? state = null, CustomResourceOptions? options = null)
            : base("doppler:index/projectMemberServiceAccount:ProjectMemberServiceAccount", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pulumiverse",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ProjectMemberServiceAccount resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ProjectMemberServiceAccount Get(string name, Input<string> id, ProjectMemberServiceAccountState? state = null, CustomResourceOptions? options = null)
        {
            return new ProjectMemberServiceAccount(name, id, state, options);
        }
    }

    public sealed class ProjectMemberServiceAccountArgs : global::Pulumi.ResourceArgs
    {
        [Input("environments")]
        private InputList<string>? _environments;

        /// <summary>
        /// The environments in the project where this access will apply (null or omitted for roles with access to all environments)
        /// </summary>
        public InputList<string> Environments
        {
            get => _environments ?? (_environments = new InputList<string>());
            set => _environments = value;
        }

        /// <summary>
        /// The name of the Doppler project where the access is applied
        /// </summary>
        [Input("project", required: true)]
        public Input<string> Project { get; set; } = null!;

        /// <summary>
        /// The project role identifier for the access
        /// </summary>
        [Input("role", required: true)]
        public Input<string> Role { get; set; } = null!;

        /// <summary>
        /// The slug of the Doppler service account
        /// </summary>
        [Input("serviceAccountSlug", required: true)]
        public Input<string> ServiceAccountSlug { get; set; } = null!;

        public ProjectMemberServiceAccountArgs()
        {
        }
        public static new ProjectMemberServiceAccountArgs Empty => new ProjectMemberServiceAccountArgs();
    }

    public sealed class ProjectMemberServiceAccountState : global::Pulumi.ResourceArgs
    {
        [Input("environments")]
        private InputList<string>? _environments;

        /// <summary>
        /// The environments in the project where this access will apply (null or omitted for roles with access to all environments)
        /// </summary>
        public InputList<string> Environments
        {
            get => _environments ?? (_environments = new InputList<string>());
            set => _environments = value;
        }

        /// <summary>
        /// The name of the Doppler project where the access is applied
        /// </summary>
        [Input("project")]
        public Input<string>? Project { get; set; }

        /// <summary>
        /// The project role identifier for the access
        /// </summary>
        [Input("role")]
        public Input<string>? Role { get; set; }

        /// <summary>
        /// The slug of the Doppler service account
        /// </summary>
        [Input("serviceAccountSlug")]
        public Input<string>? ServiceAccountSlug { get; set; }

        public ProjectMemberServiceAccountState()
        {
        }
        public static new ProjectMemberServiceAccountState Empty => new ProjectMemberServiceAccountState();
    }
}
