// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package secretssync

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-doppler/sdk/go/doppler/internal"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "doppler:secretsSync/awsParameterStore:AwsParameterStore":
		r = &AwsParameterStore{}
	case "doppler:secretsSync/awsSecretsManager:AwsSecretsManager":
		r = &AwsSecretsManager{}
	case "doppler:secretsSync/circleci:Circleci":
		r = &Circleci{}
	case "doppler:secretsSync/flyio:Flyio":
		r = &Flyio{}
	case "doppler:secretsSync/githubActions:GithubActions":
		r = &GithubActions{}
	case "doppler:secretsSync/terraformCloud:TerraformCloud":
		r = &TerraformCloud{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := internal.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"doppler",
		"secretsSync/awsParameterStore",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"doppler",
		"secretsSync/awsSecretsManager",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"doppler",
		"secretsSync/circleci",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"doppler",
		"secretsSync/flyio",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"doppler",
		"secretsSync/githubActions",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"doppler",
		"secretsSync/terraformCloud",
		&module{version},
	)
}
