# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .branch_config import *
from .environment import *
from .project import *
from .provider import *
from .secret import *
from .secrets import *
from .service_token import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumiverse_doppler.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumiverse_doppler.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "doppler",
  "mod": "index/branchConfig",
  "fqn": "pulumiverse_doppler",
  "classes": {
   "doppler:index/branchConfig:BranchConfig": "BranchConfig"
  }
 },
 {
  "pkg": "doppler",
  "mod": "index/environment",
  "fqn": "pulumiverse_doppler",
  "classes": {
   "doppler:index/environment:Environment": "Environment"
  }
 },
 {
  "pkg": "doppler",
  "mod": "index/project",
  "fqn": "pulumiverse_doppler",
  "classes": {
   "doppler:index/project:Project": "Project"
  }
 },
 {
  "pkg": "doppler",
  "mod": "index/secret",
  "fqn": "pulumiverse_doppler",
  "classes": {
   "doppler:index/secret:Secret": "Secret"
  }
 },
 {
  "pkg": "doppler",
  "mod": "index/serviceToken",
  "fqn": "pulumiverse_doppler",
  "classes": {
   "doppler:index/serviceToken:ServiceToken": "ServiceToken"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "doppler",
  "token": "pulumi:providers:doppler",
  "fqn": "pulumiverse_doppler",
  "class": "Provider"
 }
]
"""
)
