// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Doppler.Outputs
{

    [OutputType]
    public sealed class WebhookAuthentication
    {
        public readonly string? Password;
        public readonly string? Token;
        public readonly string Type;
        public readonly string? Username;

        [OutputConstructor]
        private WebhookAuthentication(
            string? password,

            string? token,

            string type,

            string? username)
        {
            Password = password;
            Token = token;
            Type = type;
            Username = username;
        }
    }
}
