# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

dopplerToken: Optional[str]
"""
A Doppler token, either a personal or service token. This can also be set via the DOPPLER_TOKEN environment variable.
"""

host: Optional[str]
"""
The Doppler API host (i.e. https://api.doppler.com). This can also be set via the DOPPLER_API_HOST environment variable.
"""

verifyTls: Optional[bool]
"""
Whether or not to verify TLS. This can also be set via the DOPPLER_VERIFY_TLS environment variable.
"""

