// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Manage an AWS Parameter Store Doppler integration.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 * import * as doppler from "@pulumiverse/doppler";
 *
 * const dopplerParameterStore = new aws.iam.Role("dopplerParameterStore", {
 *     assumeRolePolicy: JSON.stringify({
 *         Version: "2012-10-17",
 *         Statement: [{
 *             Effect: "Allow",
 *             Action: "sts:AssumeRole",
 *             Principal: {
 *                 AWS: "arn:aws:iam::299900769157:user/doppler-integration-operator",
 *             },
 *             Condition: {
 *                 StringEquals: {
 *                     "sts:ExternalId": "<YOUR_WORKPLACE_SLUG>",
 *                 },
 *             },
 *         }],
 *     }),
 *     inlinePolicies: [{
 *         policy: JSON.stringify({
 *             Version: "2012-10-17",
 *             Statement: [{
 *                 Action: [
 *                     "ssm:PutParameter",
 *                     "ssm:LabelParameterVersion",
 *                     "ssm:DeleteParameter",
 *                     "ssm:RemoveTagsFromResource",
 *                     "ssm:GetParameterHistory",
 *                     "ssm:AddTagsToResource",
 *                     "ssm:GetParametersByPath",
 *                     "ssm:GetParameters",
 *                     "ssm:GetParameter",
 *                     "ssm:DeleteParameters",
 *                 ],
 *                 Effect: "Allow",
 *                 Resource: "*",
 *             }],
 *         }),
 *     }],
 * });
 * const prod = new doppler.integration.AwsParameterStore("prod", {
 *     name: "Production",
 *     assumeRoleArn: dopplerParameterStore.arn,
 * });
 * const backendProd = new doppler.secretssync.AwsParameterStore("backendProd", {
 *     integration: prod.id,
 *     project: "backend",
 *     config: "prd",
 *     region: "us-east-1",
 *     path: "/backend/",
 *     secureString: true,
 *     tags: {
 *         myTag: "enabled",
 *     },
 * });
 * ```
 */
export class AwsParameterStore extends pulumi.CustomResource {
    /**
     * Get an existing AwsParameterStore resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AwsParameterStoreState, opts?: pulumi.CustomResourceOptions): AwsParameterStore {
        return new AwsParameterStore(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'doppler:integration/awsParameterStore:AwsParameterStore';

    /**
     * Returns true if the given object is an instance of AwsParameterStore.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AwsParameterStore {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AwsParameterStore.__pulumiType;
    }

    /**
     * The ARN of the AWS role for Doppler to assume
     */
    public readonly assumeRoleArn!: pulumi.Output<string>;
    /**
     * The name of the integration
     */
    public readonly name!: pulumi.Output<string>;

    /**
     * Create a AwsParameterStore resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AwsParameterStoreArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AwsParameterStoreArgs | AwsParameterStoreState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AwsParameterStoreState | undefined;
            resourceInputs["assumeRoleArn"] = state ? state.assumeRoleArn : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
        } else {
            const args = argsOrState as AwsParameterStoreArgs | undefined;
            if ((!args || args.assumeRoleArn === undefined) && !opts.urn) {
                throw new Error("Missing required property 'assumeRoleArn'");
            }
            if ((!args || args.name === undefined) && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["assumeRoleArn"] = args ? args.assumeRoleArn : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AwsParameterStore.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering AwsParameterStore resources.
 */
export interface AwsParameterStoreState {
    /**
     * The ARN of the AWS role for Doppler to assume
     */
    assumeRoleArn?: pulumi.Input<string>;
    /**
     * The name of the integration
     */
    name?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a AwsParameterStore resource.
 */
export interface AwsParameterStoreArgs {
    /**
     * The ARN of the AWS role for Doppler to assume
     */
    assumeRoleArn: pulumi.Input<string>;
    /**
     * The name of the integration
     */
    name: pulumi.Input<string>;
}
