// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manage a Doppler user/group membership.
 *
 * **Note:** You can also exclusively manage all memberships in a group with a single resource.
 * See the `doppler.GroupMembers` resource for more information.
 *
 * ## Import
 *
 * import using the group slug from the URL:
 *
 * https://dashboard.doppler.com/workplace/[workplace-slug]/team/groups/[group-slug]
 *
 * and the user slug from the URL:
 *
 * https://dashboard.doppler.com/workplace/[workplace-slug]/team/users/[user-slug]
 *
 * ```sh
 * $ pulumi import doppler:index/groupMember:GroupMember default <group-slug>.workplace_user.<user-slug>
 * ```
 */
export class GroupMember extends pulumi.CustomResource {
    /**
     * Get an existing GroupMember resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: GroupMemberState, opts?: pulumi.CustomResourceOptions): GroupMember {
        return new GroupMember(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'doppler:index/groupMember:GroupMember';

    /**
     * Returns true if the given object is an instance of GroupMember.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is GroupMember {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === GroupMember.__pulumiType;
    }

    /**
     * The slug of the Doppler group
     */
    public readonly groupSlug!: pulumi.Output<string>;
    /**
     * The slug of the Doppler workplace user
     */
    public readonly userSlug!: pulumi.Output<string>;

    /**
     * Create a GroupMember resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: GroupMemberArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: GroupMemberArgs | GroupMemberState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as GroupMemberState | undefined;
            resourceInputs["groupSlug"] = state ? state.groupSlug : undefined;
            resourceInputs["userSlug"] = state ? state.userSlug : undefined;
        } else {
            const args = argsOrState as GroupMemberArgs | undefined;
            if ((!args || args.groupSlug === undefined) && !opts.urn) {
                throw new Error("Missing required property 'groupSlug'");
            }
            if ((!args || args.userSlug === undefined) && !opts.urn) {
                throw new Error("Missing required property 'userSlug'");
            }
            resourceInputs["groupSlug"] = args ? args.groupSlug : undefined;
            resourceInputs["userSlug"] = args ? args.userSlug : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(GroupMember.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering GroupMember resources.
 */
export interface GroupMemberState {
    /**
     * The slug of the Doppler group
     */
    groupSlug?: pulumi.Input<string>;
    /**
     * The slug of the Doppler workplace user
     */
    userSlug?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a GroupMember resource.
 */
export interface GroupMemberArgs {
    /**
     * The slug of the Doppler group
     */
    groupSlug: pulumi.Input<string>;
    /**
     * The slug of the Doppler workplace user
     */
    userSlug: pulumi.Input<string>;
}
