// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { ConfigArgs, ConfigState } from "./config";
export type Config = import("./config").Config;
export const Config: typeof import("./config").Config = null as any;
utilities.lazyLoad(exports, ["Config"], () => require("./config"));

export { EnvironmentArgs, EnvironmentState } from "./environment";
export type Environment = import("./environment").Environment;
export const Environment: typeof import("./environment").Environment = null as any;
utilities.lazyLoad(exports, ["Environment"], () => require("./environment"));

export { ProjectArgs, ProjectState } from "./project";
export type Project = import("./project").Project;
export const Project: typeof import("./project").Project = null as any;
utilities.lazyLoad(exports, ["Project"], () => require("./project"));

export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));

export { SecretArgs, SecretState } from "./secret";
export type Secret = import("./secret").Secret;
export const Secret: typeof import("./secret").Secret = null as any;
utilities.lazyLoad(exports, ["Secret"], () => require("./secret"));

export { SecretsArgs, SecretsResult, SecretsOutputArgs } from "./secrets";
export const secrets: typeof import("./secrets").secrets = null as any;
export const secretsOutput: typeof import("./secrets").secretsOutput = null as any;
utilities.lazyLoad(exports, ["secrets","secretsOutput"], () => require("./secrets"));

export { ServiceTokenArgs, ServiceTokenState } from "./serviceToken";
export type ServiceToken = import("./serviceToken").ServiceToken;
export const ServiceToken: typeof import("./serviceToken").ServiceToken = null as any;
utilities.lazyLoad(exports, ["ServiceToken"], () => require("./serviceToken"));


// Export sub-modules:
import * as config from "./config";

export {
    config,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "doppler:index/config:Config":
                return new Config(name, <any>undefined, { urn })
            case "doppler:index/environment:Environment":
                return new Environment(name, <any>undefined, { urn })
            case "doppler:index/project:Project":
                return new Project(name, <any>undefined, { urn })
            case "doppler:index/secret:Secret":
                return new Secret(name, <any>undefined, { urn })
            case "doppler:index/serviceToken:ServiceToken":
                return new ServiceToken(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("doppler", "index/config", _module)
pulumi.runtime.registerResourceModule("doppler", "index/environment", _module)
pulumi.runtime.registerResourceModule("doppler", "index/project", _module)
pulumi.runtime.registerResourceModule("doppler", "index/secret", _module)
pulumi.runtime.registerResourceModule("doppler", "index/serviceToken", _module)
pulumi.runtime.registerResourcePackage("doppler", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:doppler") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
