// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Webhook extends pulumi.CustomResource {
    /**
     * Get an existing Webhook resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: WebhookState, opts?: pulumi.CustomResourceOptions): Webhook {
        return new Webhook(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'doppler:index/webhook:Webhook';

    /**
     * Returns true if the given object is an instance of Webhook.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Webhook {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Webhook.__pulumiType;
    }

    /**
     * Authentication method used by the webhook
     */
    public readonly authentication!: pulumi.Output<outputs.WebhookAuthentication | undefined>;
    /**
     * Whether the webhook is enabled or disabled.  Default to true.
     */
    public readonly enabled!: pulumi.Output<boolean | undefined>;
    /**
     * Configs this webhook will trigger for
     */
    public readonly enabledConfigs!: pulumi.Output<string[] | undefined>;
    /**
     * The webhook's payload as a JSON string.  Leave empty to use the default webhook payload
     */
    public readonly payload!: pulumi.Output<string | undefined>;
    /**
     * The name of the Doppler project where the webhook is located
     */
    public readonly project!: pulumi.Output<string>;
    /**
     * Secret used for request signing
     */
    public readonly secret!: pulumi.Output<string | undefined>;
    /**
     * The slug of the Webhook
     */
    public /*out*/ readonly slug!: pulumi.Output<string>;
    /**
     * The URL of the webhook endpoint
     */
    public readonly url!: pulumi.Output<string>;

    /**
     * Create a Webhook resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: WebhookArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: WebhookArgs | WebhookState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as WebhookState | undefined;
            resourceInputs["authentication"] = state ? state.authentication : undefined;
            resourceInputs["enabled"] = state ? state.enabled : undefined;
            resourceInputs["enabledConfigs"] = state ? state.enabledConfigs : undefined;
            resourceInputs["payload"] = state ? state.payload : undefined;
            resourceInputs["project"] = state ? state.project : undefined;
            resourceInputs["secret"] = state ? state.secret : undefined;
            resourceInputs["slug"] = state ? state.slug : undefined;
            resourceInputs["url"] = state ? state.url : undefined;
        } else {
            const args = argsOrState as WebhookArgs | undefined;
            if ((!args || args.project === undefined) && !opts.urn) {
                throw new Error("Missing required property 'project'");
            }
            if ((!args || args.url === undefined) && !opts.urn) {
                throw new Error("Missing required property 'url'");
            }
            resourceInputs["authentication"] = args ? args.authentication : undefined;
            resourceInputs["enabled"] = args ? args.enabled : undefined;
            resourceInputs["enabledConfigs"] = args ? args.enabledConfigs : undefined;
            resourceInputs["payload"] = args?.payload ? pulumi.secret(args.payload) : undefined;
            resourceInputs["project"] = args ? args.project : undefined;
            resourceInputs["secret"] = args?.secret ? pulumi.secret(args.secret) : undefined;
            resourceInputs["url"] = args ? args.url : undefined;
            resourceInputs["slug"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["payload", "secret"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Webhook.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Webhook resources.
 */
export interface WebhookState {
    /**
     * Authentication method used by the webhook
     */
    authentication?: pulumi.Input<inputs.WebhookAuthentication>;
    /**
     * Whether the webhook is enabled or disabled.  Default to true.
     */
    enabled?: pulumi.Input<boolean>;
    /**
     * Configs this webhook will trigger for
     */
    enabledConfigs?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The webhook's payload as a JSON string.  Leave empty to use the default webhook payload
     */
    payload?: pulumi.Input<string>;
    /**
     * The name of the Doppler project where the webhook is located
     */
    project?: pulumi.Input<string>;
    /**
     * Secret used for request signing
     */
    secret?: pulumi.Input<string>;
    /**
     * The slug of the Webhook
     */
    slug?: pulumi.Input<string>;
    /**
     * The URL of the webhook endpoint
     */
    url?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Webhook resource.
 */
export interface WebhookArgs {
    /**
     * Authentication method used by the webhook
     */
    authentication?: pulumi.Input<inputs.WebhookAuthentication>;
    /**
     * Whether the webhook is enabled or disabled.  Default to true.
     */
    enabled?: pulumi.Input<boolean>;
    /**
     * Configs this webhook will trigger for
     */
    enabledConfigs?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The webhook's payload as a JSON string.  Leave empty to use the default webhook payload
     */
    payload?: pulumi.Input<string>;
    /**
     * The name of the Doppler project where the webhook is located
     */
    project: pulumi.Input<string>;
    /**
     * Secret used for request signing
     */
    secret?: pulumi.Input<string>;
    /**
     * The URL of the webhook endpoint
     */
    url: pulumi.Input<string>;
}
